### ISSUE TITLE
Avoiding exceptions in command line interface

### ISSUE THREAD

**Issue by dch0ph** [CCP-NC/soprano#20]
I would reserve exceptions for internal errors, rather than general invalid user input. e.g. an innocent:
soprano nmr -o test CONGRS_nmr.magres

generates:
Writing output to test
Traceback (most recent call last):
  File "C:\Users\PAUL\anaconda3\envs\sopranotest\Scripts\soprano-script.py", line 33, in <module>
    sys.exit(load_entry_point('Soprano', 'console_scripts', 'soprano')())
  File "C:\Users\PAUL\anaconda3\envs\sopranotest\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\PAUL\anaconda3\envs\sopranotest\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\PAUL\anaconda3\envs\sopranotest\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\PAUL\anaconda3\envs\sopranotest\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\PAUL\anaconda3\envs\sopranotest\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "d:\dch0ph\ccp-nc\jkshenton-soprano\soprano\scripts\nmr.py", line 351, in nmr
    print_results(dfs, output, output_format, verbose)
  File "d:\dch0ph\ccp-nc\jkshenton-soprano\soprano\scripts\cli_utils.py", line 510, in print_results
    raise ValueError(f'Unknown output format: {output_format}')
ValueError: Unknown output format:

!

I would use sys.exit("error message") for this kind of thing.

I would specifically trap "no file extension" provided to print a helpful message about output type being deduced from file extension (and values accepted).

Could add .txt for tab separated?

Paul

**Comment by jkshenton** [comment]
Thanks Paul. Most problems with arguments should be handled more gracefully. I've added in a fix for the output file types. 

I can't do the same with the plot output formats because the allowed set of types depends on what backend people use on their system. We could restrict people to a limited set of output formats - most backends support png, pdf, ps, eps and svg. This would cover most use cases but people might want some more niche formats.
